# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(774, 595)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_simple = QtWidgets.QWidget()
        self.tab_simple.setObjectName("tab_simple")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_simple)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_audioquality = QtWidgets.QLabel(self.tab_simple)
        self.label_audioquality.setObjectName("label_audioquality")
        self.gridLayout_2.addWidget(self.label_audioquality, 2, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(250, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 1, 1, 1)
        self.presetbox = QtWidgets.QComboBox(self.tab_simple)
        self.presetbox.setObjectName("presetbox")
        self.gridLayout_2.addWidget(self.presetbox, 1, 3, 1, 1)
        self.audioqualitybox = QtWidgets.QComboBox(self.tab_simple)
        self.audioqualitybox.setObjectName("audioqualitybox")
        self.gridLayout_2.addWidget(self.audioqualitybox, 2, 3, 1, 1)
        self.label_preset = QtWidgets.QLabel(self.tab_simple)
        self.label_preset.setObjectName("label_preset")
        self.gridLayout_2.addWidget(self.label_preset, 1, 2, 1, 1)
        self.checkBox_audio = QtWidgets.QCheckBox(self.tab_simple)
        self.checkBox_audio.setMinimumSize(QtCore.QSize(0, 0))
        self.checkBox_audio.setChecked(False)
        self.checkBox_audio.setObjectName("checkBox_audio")
        self.gridLayout_2.addWidget(self.checkBox_audio, 2, 0, 1, 1)
        self.checkBox_twopass = QtWidgets.QCheckBox(self.tab_simple)
        self.checkBox_twopass.setChecked(True)
        self.checkBox_twopass.setObjectName("checkBox_twopass")
        self.gridLayout_2.addWidget(self.checkBox_twopass, 1, 0, 1, 1)
        self.label_quality = QtWidgets.QLabel(self.tab_simple)
        self.label_quality.setObjectName("label_quality")
        self.gridLayout_2.addWidget(self.label_quality, 0, 2, 1, 1)
        self.comboBox_quality = QtWidgets.QComboBox(self.tab_simple)
        self.comboBox_quality.setObjectName("comboBox_quality")
        self.gridLayout_2.addWidget(self.comboBox_quality, 0, 3, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 242, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem1, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_simple, "")
        self.tab_advanced = QtWidgets.QWidget()
        self.tab_advanced.setObjectName("tab_advanced")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_advanced)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_hdr = QtWidgets.QCheckBox(self.tab_advanced)
        self.checkBox_hdr.setObjectName("checkBox_hdr")
        self.gridLayout.addWidget(self.checkBox_hdr, 2, 4, 1, 1)
        self.label_audio = QtWidgets.QLabel(self.tab_advanced)
        self.label_audio.setObjectName("label_audio")
        self.gridLayout.addWidget(self.label_audio, 0, 3, 1, 1)
        self.checkBox_minsplit = QtWidgets.QCheckBox(self.tab_advanced)
        self.checkBox_minsplit.setObjectName("checkBox_minsplit")
        self.gridLayout.addWidget(self.checkBox_minsplit, 4, 4, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_advanced)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_jobs = QtWidgets.QLabel(self.tab_advanced)
        self.label_jobs.setObjectName("label_jobs")
        self.gridLayout.addWidget(self.label_jobs, 3, 0, 1, 1)
        self.label_boost = QtWidgets.QLabel(self.tab_advanced)
        self.label_boost.setObjectName("label_boost")
        self.gridLayout.addWidget(self.label_boost, 1, 3, 1, 1)
        self.label_split = QtWidgets.QLabel(self.tab_advanced)
        self.label_split.setObjectName("label_split")
        self.gridLayout.addWidget(self.label_split, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(140, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 4, 2, 1, 1)
        self.spinBox_speed = QtWidgets.QSpinBox(self.tab_advanced)
        self.spinBox_speed.setMaximum(8)
        self.spinBox_speed.setProperty("value", 4)
        self.spinBox_speed.setObjectName("spinBox_speed")
        self.gridLayout.addWidget(self.spinBox_speed, 2, 1, 1, 1)
        self.comboBox_colorspace = QtWidgets.QComboBox(self.tab_advanced)
        self.comboBox_colorspace.setObjectName("comboBox_colorspace")
        self.gridLayout.addWidget(self.comboBox_colorspace, 5, 1, 1, 1)
        self.spinBox_jobs = QtWidgets.QSpinBox(self.tab_advanced)
        self.spinBox_jobs.setMinimum(0)
        self.spinBox_jobs.setMaximum(128)
        self.spinBox_jobs.setSingleStep(1)
        self.spinBox_jobs.setProperty("value", 0)
        self.spinBox_jobs.setObjectName("spinBox_jobs")
        self.gridLayout.addWidget(self.spinBox_jobs, 3, 1, 1, 1)
        self.comboBox_inputFormat = QtWidgets.QComboBox(self.tab_advanced)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_inputFormat.sizePolicy().hasHeightForWidth())
        self.comboBox_inputFormat.setSizePolicy(sizePolicy)
        self.comboBox_inputFormat.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_inputFormat.setObjectName("comboBox_inputFormat")
        self.gridLayout.addWidget(self.comboBox_inputFormat, 4, 1, 1, 1)
        self.label_inputformat = QtWidgets.QLabel(self.tab_advanced)
        self.label_inputformat.setObjectName("label_inputformat")
        self.gridLayout.addWidget(self.label_inputformat, 4, 0, 1, 1)
        self.label_q = QtWidgets.QLabel(self.tab_advanced)
        self.label_q.setObjectName("label_q")
        self.gridLayout.addWidget(self.label_q, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_advanced)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.spinBox_boost = QtWidgets.QSpinBox(self.tab_advanced)
        self.spinBox_boost.setMaximum(50)
        self.spinBox_boost.setProperty("value", 0)
        self.spinBox_boost.setObjectName("spinBox_boost")
        self.gridLayout.addWidget(self.spinBox_boost, 1, 4, 1, 1)
        self.checkBox_tempfolder = QtWidgets.QCheckBox(self.tab_advanced)
        self.checkBox_tempfolder.setObjectName("checkBox_tempfolder")
        self.gridLayout.addWidget(self.checkBox_tempfolder, 3, 4, 1, 1)
        self.checkBox_rtenc = QtWidgets.QCheckBox(self.tab_advanced)
        self.checkBox_rtenc.setObjectName("checkBox_rtenc")
        self.gridLayout.addWidget(self.checkBox_rtenc, 4, 3, 1, 1)
        self.spinBox_audio = QtWidgets.QSpinBox(self.tab_advanced)
        self.spinBox_audio.setReadOnly(True)
        self.spinBox_audio.setMinimum(8)
        self.spinBox_audio.setMaximum(480)
        self.spinBox_audio.setSingleStep(8)
        self.spinBox_audio.setProperty("value", 96)
        self.spinBox_audio.setObjectName("spinBox_audio")
        self.gridLayout.addWidget(self.spinBox_audio, 0, 4, 1, 1)
        self.spinBox_split = QtWidgets.QSpinBox(self.tab_advanced)
        self.spinBox_split.setMinimum(1)
        self.spinBox_split.setMaximum(99)
        self.spinBox_split.setProperty("value", 30)
        self.spinBox_split.setObjectName("spinBox_split")
        self.gridLayout.addWidget(self.spinBox_split, 1, 1, 1, 1)
        self.spinBox_quality = QtWidgets.QSpinBox(self.tab_advanced)
        self.spinBox_quality.setMinimum(0)
        self.spinBox_quality.setMaximum(50)
        self.spinBox_quality.setObjectName("spinBox_quality")
        self.gridLayout.addWidget(self.spinBox_quality, 0, 1, 1, 1)
        self.checkBox_resume = QtWidgets.QCheckBox(self.tab_advanced)
        self.checkBox_resume.setObjectName("checkBox_resume")
        self.gridLayout.addWidget(self.checkBox_resume, 3, 3, 1, 1)
        self.checkBox_bitrate = QtWidgets.QCheckBox(self.tab_advanced)
        self.checkBox_bitrate.setObjectName("checkBox_bitrate")
        self.gridLayout.addWidget(self.checkBox_bitrate, 2, 3, 1, 1)
        self.lineEdit_colordata = QtWidgets.QLineEdit(self.tab_advanced)
        self.lineEdit_colordata.setEnabled(False)
        self.lineEdit_colordata.setText("")
        self.lineEdit_colordata.setObjectName("lineEdit_colordata")
        self.gridLayout.addWidget(self.lineEdit_colordata, 6, 0, 1, 5)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem3, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_advanced, "")
        self.gridLayout_3.addWidget(self.tabWidget, 1, 0, 1, 4)
        self.progressBar_total = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_total.setEnabled(False)
        self.progressBar_total.setProperty("value", 0)
        self.progressBar_total.setObjectName("progressBar_total")
        self.gridLayout_3.addWidget(self.progressBar_total, 2, 2, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.inputPath = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputPath.sizePolicy().hasHeightForWidth())
        self.inputPath.setSizePolicy(sizePolicy)
        self.inputPath.setText("")
        self.inputPath.setTextFormat(QtCore.Qt.PlainText)
        self.inputPath.setWordWrap(True)
        self.inputPath.setObjectName("inputPath")
        self.gridLayout_4.addWidget(self.inputPath, 0, 1, 1, 1)
        self.inputFileChoose = QtWidgets.QPushButton(self.centralwidget)
        self.inputFileChoose.setMinimumSize(QtCore.QSize(140, 0))
        self.inputFileChoose.setMaximumSize(QtCore.QSize(140, 16777215))
        self.inputFileChoose.setObjectName("inputFileChoose")
        self.gridLayout_4.addWidget(self.inputFileChoose, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 1, 0, 1, 1)
        self.outputPath = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputPath.sizePolicy().hasHeightForWidth())
        self.outputPath.setSizePolicy(sizePolicy)
        self.outputPath.setText("")
        self.outputPath.setTextFormat(QtCore.Qt.PlainText)
        self.outputPath.setWordWrap(True)
        self.outputPath.setObjectName("outputPath")
        self.gridLayout_4.addWidget(self.outputPath, 1, 1, 1, 1)
        self.outputFileChoose = QtWidgets.QPushButton(self.centralwidget)
        self.outputFileChoose.setObjectName("outputFileChoose")
        self.gridLayout_4.addWidget(self.outputFileChoose, 1, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 0, 0, 1, 4)
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_status.sizePolicy().hasHeightForWidth())
        self.label_status.setSizePolicy(sizePolicy)
        self.label_status.setMinimumSize(QtCore.QSize(180, 0))
        self.label_status.setText("")
        self.label_status.setObjectName("label_status")
        self.gridLayout_3.addWidget(self.label_status, 2, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setEnabled(False)
        self.pushButton.setMinimumSize(QtCore.QSize(120, 0))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 2, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 774, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_audioquality.setText(_translate("MainWindow", "Audio Quality"))
        self.label_preset.setText(_translate("MainWindow", "Speed Preset"))
        self.checkBox_audio.setText(_translate("MainWindow", "Reencode Audio"))
        self.checkBox_twopass.setText(_translate("MainWindow", "Two Pass"))
        self.label_quality.setText(_translate("MainWindow", "Quality Preset"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_simple), _translate("MainWindow", "Simple Settings"))
        self.checkBox_hdr.setText(_translate("MainWindow", "10 bit output"))
        self.label_audio.setText(_translate("MainWindow", "Audio Bitrate"))
        self.checkBox_minsplit.setText(_translate("MainWindow", "Minimal splitting"))
        self.label_6.setText(_translate("MainWindow", "cpu-used (speed)"))
        self.label_jobs.setText(_translate("MainWindow", "Jobs"))
        self.label_boost.setText(_translate("MainWindow", "Dark Boost"))
        self.label_split.setText(_translate("MainWindow", "Split threshold"))
        self.label_inputformat.setText(_translate("MainWindow", "Input Format"))
        self.label_q.setText(_translate("MainWindow", "Q factor"))
        self.label_2.setText(_translate("MainWindow", "Input Colordata"))
        self.checkBox_tempfolder.setText(_translate("MainWindow", "Keep temp folder"))
        self.checkBox_rtenc.setText(_translate("MainWindow", "Realtime Encoding"))
        self.checkBox_resume.setText(_translate("MainWindow", "Resume Encode"))
        self.checkBox_bitrate.setText(_translate("MainWindow", "Use Bitrate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_advanced), _translate("MainWindow", "Advanced"))
        self.label.setText(_translate("MainWindow", "Source"))
        self.inputFileChoose.setText(_translate("MainWindow", "Open..."))
        self.label_5.setText(_translate("MainWindow", "Output"))
        self.outputFileChoose.setText(_translate("MainWindow", "Save to..."))
        self.pushButton.setText(_translate("MainWindow", "Encode"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open Video"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save Video"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionExit.setText(_translate("MainWindow", "Quit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
