# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 421)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setEnabled(False)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 8, 4, 1, 1)
        self.label_audio = QtWidgets.QLabel(self.centralwidget)
        self.label_audio.setObjectName("label_audio")
        self.gridLayout.addWidget(self.label_audio, 7, 1, 1, 3)
        self.spinBox_split = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_split.setMinimum(1)
        self.spinBox_split.setMaximum(99)
        self.spinBox_split.setProperty("value", 30)
        self.spinBox_split.setObjectName("spinBox_split")
        self.gridLayout.addWidget(self.spinBox_split, 5, 1, 1, 1)
        self.inputPath = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputPath.sizePolicy().hasHeightForWidth())
        self.inputPath.setSizePolicy(sizePolicy)
        self.inputPath.setTextFormat(QtCore.Qt.PlainText)
        self.inputPath.setWordWrap(True)
        self.inputPath.setObjectName("inputPath")
        self.gridLayout.addWidget(self.inputPath, 1, 0, 1, 4)
        self.outputFileChoose = QtWidgets.QPushButton(self.centralwidget)
        self.outputFileChoose.setObjectName("outputFileChoose")
        self.gridLayout.addWidget(self.outputFileChoose, 2, 4, 1, 1)
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        self.label_status.setText("")
        self.label_status.setObjectName("label_status")
        self.gridLayout.addWidget(self.label_status, 8, 0, 1, 1)
        self.outputPath = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.outputPath.sizePolicy().hasHeightForWidth())
        self.outputPath.setSizePolicy(sizePolicy)
        self.outputPath.setTextFormat(QtCore.Qt.PlainText)
        self.outputPath.setWordWrap(True)
        self.outputPath.setObjectName("outputPath")
        self.gridLayout.addWidget(self.outputPath, 2, 0, 1, 4)
        self.label_boost = QtWidgets.QLabel(self.centralwidget)
        self.label_boost.setObjectName("label_boost")
        self.gridLayout.addWidget(self.label_boost, 5, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 1, 1, 1)
        self.progressBar_total = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_total.setEnabled(False)
        self.progressBar_total.setProperty("value", 0)
        self.progressBar_total.setObjectName("progressBar_total")
        self.gridLayout.addWidget(self.progressBar_total, 9, 0, 1, 5)
        self.spinBox_boost = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_boost.setMaximum(50)
        self.spinBox_boost.setProperty("value", 0)
        self.spinBox_boost.setObjectName("spinBox_boost")
        self.gridLayout.addWidget(self.spinBox_boost, 5, 4, 1, 1)
        self.checkBox_hdr = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_hdr.setObjectName("checkBox_hdr")
        self.gridLayout.addWidget(self.checkBox_hdr, 6, 0, 1, 1)
        self.label_q = QtWidgets.QLabel(self.centralwidget)
        self.label_q.setObjectName("label_q")
        self.gridLayout.addWidget(self.label_q, 3, 1, 1, 3)
        self.checkBox_audio = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_audio.setChecked(False)
        self.checkBox_audio.setObjectName("checkBox_audio")
        self.gridLayout.addWidget(self.checkBox_audio, 7, 0, 1, 1)
        self.spinBox_audio = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_audio.setReadOnly(True)
        self.spinBox_audio.setMinimum(32)
        self.spinBox_audio.setMaximum(256)
        self.spinBox_audio.setSingleStep(8)
        self.spinBox_audio.setProperty("value", 96)
        self.spinBox_audio.setObjectName("spinBox_audio")
        self.gridLayout.addWidget(self.spinBox_audio, 7, 4, 1, 1)
        self.label_split = QtWidgets.QLabel(self.centralwidget)
        self.label_split.setObjectName("label_split")
        self.gridLayout.addWidget(self.label_split, 5, 0, 1, 1)
        self.progressBar_status = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_status.setEnabled(False)
        self.progressBar_status.setProperty("value", 0)
        self.progressBar_status.setObjectName("progressBar_status")
        self.gridLayout.addWidget(self.progressBar_status, 8, 1, 1, 3)
        self.checkBox_bitrate = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_bitrate.setObjectName("checkBox_bitrate")
        self.gridLayout.addWidget(self.checkBox_bitrate, 3, 0, 1, 1)
        self.spinBox_quality = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_quality.setMinimum(0)
        self.spinBox_quality.setMaximum(50)
        self.spinBox_quality.setObjectName("spinBox_quality")
        self.gridLayout.addWidget(self.spinBox_quality, 3, 4, 1, 1)
        self.inputFileChoose = QtWidgets.QPushButton(self.centralwidget)
        self.inputFileChoose.setMaximumSize(QtCore.QSize(140, 16777215))
        self.inputFileChoose.setObjectName("inputFileChoose")
        self.gridLayout.addWidget(self.inputFileChoose, 1, 4, 1, 1)
        self.spinBox_speed = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_speed.setMaximum(5)
        self.spinBox_speed.setProperty("value", 3)
        self.spinBox_speed.setObjectName("spinBox_speed")
        self.gridLayout.addWidget(self.spinBox_speed, 6, 2, 1, 1)
        self.label_jobs = QtWidgets.QLabel(self.centralwidget)
        self.label_jobs.setObjectName("label_jobs")
        self.gridLayout.addWidget(self.label_jobs, 6, 3, 1, 1)
        self.spinBox_jobs = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_jobs.setMinimum(1)
        self.spinBox_jobs.setMaximum(128)
        self.spinBox_jobs.setObjectName("spinBox_jobs")
        self.gridLayout.addWidget(self.spinBox_jobs, 6, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 34))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Encode"))
        self.label_audio.setText(_translate("MainWindow", "Audio Bitrate"))
        self.inputPath.setText(_translate("MainWindow", "/"))
        self.outputFileChoose.setText(_translate("MainWindow", "Output"))
        self.outputPath.setText(_translate("MainWindow", "/"))
        self.label_boost.setText(_translate("MainWindow", "Dark Boost"))
        self.label_2.setText(_translate("MainWindow", "speed"))
        self.checkBox_hdr.setText(_translate("MainWindow", "10 bit"))
        self.label_q.setText(_translate("MainWindow", "Q factor"))
        self.checkBox_audio.setText(_translate("MainWindow", "Reencode Audio"))
        self.label_split.setText(_translate("MainWindow", "Split threshold"))
        self.progressBar_status.setFormat(_translate("MainWindow", "%p%"))
        self.checkBox_bitrate.setText(_translate("MainWindow", "Use Bitrate"))
        self.inputFileChoose.setText(_translate("MainWindow", "Input File"))
        self.label_jobs.setText(_translate("MainWindow", "Jobs"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open Video"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save Video"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
